import React, { Component } from "react";
import { getComponent, Components, replaceComponent } from "meteor/vulcan:core";
import { toast, ToastContainer } from "react-toastify";

const BareUsersForm = getComponent("UsersForm");
// UsersForm is autogenerated
// This components override it and handles the password
export class UsersForm extends Component {
  constructor() {
    super();
    this.state = {
      password: null
    };
  }

  storePassword = data => {
    this.setState({ password: data._password });
  };
  setPassword = ({ _id }) => {
    Meteor.call(
      "users.setPassword",
      {
        _id,
        password: this.state.password
      },
      (err, res) => {
        if (err) {
          toast.error("Impossible de mettre à jour le mot de passe");
        } else {
          toast.success("Mot de passe mis à jour");
        }
      }
    );
  };

  render() {
    // TODO: setup callbacks
    return (
      <BareUsersForm
        submitCallback={this.storePassword}
        successCallback={this.setPassword}
        {...this.props}
      />
    );
  }
}

replaceComponent("UsersForm", UsersForm);
