/**
 * Generic page for a collection
 * Must be handled by the parent :
 * - providing the documents and callbacks
 */

import React from "react";
import {
  Components,
  Loading,
  registerComponent,
  withCurrentUser
} from "meteor/vulcan:core";
import { FormattedMessage } from "meteor/vulcan:i18n";
import { Link } from "react-router";

import moment from "moment";

const Icon = () => "ICON";

/**
 * Built sensible columns from the schema
 * @param {*} displayedSchemaFields
 */
const buildDefaultColumns = (schema, displayedFields) =>
  displayedFields.map(field => {
    let component;
    switch (schema[field].control) {
      // TODO: do the same with 'User'
      case "datetime":
        component = ({ document }) => {
          const date = document[field];
          return (
            <div>
              <div>{moment(date).format("dddd DD/MM/YYYY à HH:mm")}</div>
              <div>
                {moment.duration(moment(date).diff(moment())).humanize(true)}
              </div>
            </div>
          );
        };
        break;
      case "checkdiv":
        component = ({ document }) => {
          if (document[field] === true)
            return (
              <span>
                <Icon iconName="tick" />
                Oui
              </span>
            );
          if (document[field] === false) return <span>Non</span>;
          return (
            <span>
              <Icon iconName="help" />
              Inconnu
            </span>
          );
        };
        break;
      default:
        component = undefined;
    }
    return {
      name: field,
      component
    };
  });

const buildActionsColumn = ({
  collection,
  name = "Actions",
  baseRoute,
  editRoute
}) => ({
  name,
  component: ({ document, currentUser }) => {
    return (
      <div justify="space-around" align="center">
        <Link to={`${baseRoute}/${document._id}`}>
          <Components.Button
            className="pt-intent-primary"
            iconName="eye-open"
          />
        </Link>
        {collection.options.mutations.edit.check(currentUser, document) ? (
          <Link to={`${baseRoute}/${document._id}${editRoute}`}>
            <Components.Button className="pt-intent-primary" iconName="edit" />
          </Link>
        ) : null}
      </div>
    );
  }
});

export const CollectionPage = ({
  results = [],
  currentUser,
  loading,
  collection,
  options,
  terms = {},
  sort,
  baseRoute, // eg /customers
  newRoute = "/new", // relative to the baseRoute,
  editRoute = "/edit", // relative to the baseRoute
  addText = "Ajouter",
  tableHeaderText, // collection name
  basicColumns = [], // autogenerated columns
  customColumns = [], // already customized columns
  check
}) => (
  <Components.ShowIf
    check={typeof check !== "undefined" ? check : () => true}
    document={currentUser}
    failureComponent={
      <div>
        <div px={16} py={24}>
          <FormattedMessage id="app.noPermission" />
        </div>
      </div>
    }
  >
    <div direction="column" style={{ width: "100%" }}>
      {collection.options.mutations.new.check(currentUser) ? (
        <div px={16} py={24}>
          <Link to={`${baseRoute}${newRoute}`}>
            <Components.Button
              iconName="add"
              className="pt-large pt-intent-primary"
            >
              {addText}
            </Components.Button>
          </Link>
        </div>
      ) : null}
      <div px={16} py={24}>
        <h2>{tableHeaderText || collection.typeName || collection._name}</h2>
        {loading ? (
          <Loading />
        ) : (
          <div>
            {results.length ? (
              <div>
                <Components.Datatable
                  collection={collection}
                  options={options}
                  terms={terms}
                  showEdit={false}
                  sort={sort}
                  columns={[
                    // generate the default columns for non specific columns
                    ...buildDefaultColumns(
                      collection.options.schema,
                      basicColumns
                    ),
                    ...customColumns,
                    buildActionsColumn({
                      name: "Actions",
                      collection,
                      editRoute,
                      baseRoute
                    })
                  ]}
                />
              </div>
            ) : (
              <span>Aucune donnée à afficher pour le moment</span>
            )}
          </div>
        )}
      </div>
    </div>
  </Components.ShowIf>
);

export default CollectionPage;
registerComponent("CollectionPage", CollectionPage, withCurrentUser);
